spring.datasource.url=jdbc:postgresql://localhost:5432/skydex
spring.datasource.username=guilherme_becker
spring.datasource.password=2810amora

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true